---

- name: "alertmanager play." 
  hosts: prometheus
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    - TO: "{{ lookup('env', 'TO')}}"
    - SMTP_HOST: "{{ lookup('env', 'SMTP_HOST')}}"
    - AUTH_USERNAME: "{{ lookup('env', 'AUTH_USERNAME')}}"
    - AUTH_IDENTITY: "{{ lookup('env', 'AUTH_IDENTITY')}}"
    - AUTH_PASSWORD: "{{ lookup('env', 'AUTH_PASSWORD')}}"

  roles:
    - setup-alertmanager
