---
- name: update apt packages.
  become: true
  apt:
    update_cache: yes

- name: upgrade packages
  become: true
  apt:
    upgrade: yes

- name: install Python, Node & npm
  apt:
    pkg:
    - nodejs
    - npm
    - python3

- name: install pm2
  shell: npm install pm2 -g

