---
- name: copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: extract the app
  shell: |
    mkdir ~/app && cd ~/app
    tar xzvf ~/artifact.tar.gz

- name: start the app
  become: true
  shell: |
    cd ~/app
    npm install
    pm2 stop default
    pm2 start npm -- start

