---
- name: create app directory
  file:
    path: ~/app
    state: directory

- name: unpack artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/app

- name: start app
  become: true
  shell: |
    cd ~/app
    npm install
    pm2 stop default
    pm2 start npm -- start

