---
- name: add a new user for node exporter
  become: true
  shell: |
    id node_exporter || useradd --no-create-home node_exporter

- name: download and install prometheus node exporter
  become: true
  shell: |
    wget -c https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    tar xzvf node_exporter-1.5.0.linux-amd64.tar.gz
    cp node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.5.0.linux-amd64.tar.gz node_exporter-1.5.0.linux-amd64

- name: configure a service for node_exporter
  become: true
  shell: |
    cat <<END >/etc/systemd/system/node-exporter.service
    [Unit]
    Description=Prometheus Node Exporter Service
    After=network.target

    [Service]
    User=node_exporter
    Group=node_exporter
    Type=simple
    ExecStart=/usr/local/bin/node_exporter

    [Install]
    WantedBy=multi-user.target
    END

- name: starts node_exporter
  become: true
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter
