---
# See https://devopscube.com/install-configure-prometheus-linux/
- name: add a new user for Prometheus
  become: true
  shell: |
    useradd --no-create-home --shell /bin/false prometheus
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /var/lib/prometheus

- name: download and install Prometheus
  become: true
  shell: |
    # Download Prometheus
    wget -c https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz
    tar xzvf prometheus-2.41.0.linux-amd64.tar.gz

    # Copy Prometheus files
    cp prometheus-2.41.0.linux-amd64/prometheus /usr/local/bin/
    cp prometheus-2.41.0.linux-amd64/promtool /usr/local/bin/
    cp -r prometheus-2.41.0.linux-amd64/consoles /etc/prometheus
    cp -r prometheus-2.41.0.linux-amd64/console_libraries /etc/prometheus
    
    # Configure permissions
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries

    rm -rf prometheus-2.41.0.linux-amd64.tar.gz prometheus-2.41.0.linux-amd64

- name: copy config file
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: copy rules file
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/rules.yml

- name: Configure AWS credentials
  become: true
  shell: |
    sed -i.bak /etc/prometheus/prometheus.yml -e "s#AWS_ACCESS_KEY#${AWS_ACCESS_KEY}#" -e "s#AWS_SECRET_KEY#${AWS_SECRET_KEY}#"

- name: configure a service for Prometheus
  become: true
  shell: |
    cat <<END >/etc/systemd/system/prometheus.service
    [Unit]
    Description=Prometheus
    Wants=network-online.target
    After=network-online.target

    [Service]
    User=prometheus
    Group=prometheus
    Type=simple
    ExecStart=/usr/local/bin/prometheus \
      --config.file /etc/prometheus/prometheus.yml \
      --storage.tsdb.path /var/lib/prometheus/ \
      --web.console.templates=/etc/prometheus/consoles \
      --web.console.libraries=/etc/prometheus/console_libraries


    [Install]
    WantedBy=multi-user.target
    END

- name: starts prometheus
  become: true
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus
    systemctl status prometheus

